language: node_js
node_js:
- node
- lts/*
- '8'
- '7'
env:
  matrix:
    SAUCELABS_USER: selenium-webdriver-runner
    secure: hx7epPGO2ooX+rbQEt42RqpiPfWFp1MJyx2MmjYH+RW0YRHfl2QQ8nXNuLGFSR72V95w3A0NG26w3H30R/YfEDJAlb7KSPn5az1MJqy4lTJNHdO2GxPKDoabllu68+4TxR4rV7S9nzqi0J1JM6ag+s4TbwVU6UShEPSNx7Ea3V3ZCJtRsuZO5o0+ckbEhqM9oZYvvthetGk1yVCwAvU/Z24tDvnKPxDMN+YB+RjWDmVdKR5b91Je9DmOhN+n4IUD5OklXsAtwFPR4B2VTU8SQUyjQlQJHLwXvpwlHdq8z7uP7krthZbnNHWLjNyDuJsTWGV3ZXOaSmGjc5QNSu7N801/Ef8x55L6ZI7ukrr3jajP/1hGCqH1TEb4YvLPS0J9ZPX6Bkr7oiNXJv9q8JFm1UjfCS0bpBFId68ymVD2eX4Lw0rrkFtmP93Roc2gpSTmpssWSk0gmNImbUKa9yqHkzBbTJ1WM5XivmuH+vvb4AUANLFAZ/GqPZwNivtqqIKLRID6QryyzFd+RMZnSFiQSwzTLm12vIWaEjeQ9QeQpK80M4nOSihez1l3ZVMX6rnUGaAFBVaRhD5XyAhqaKhZRiOuDHI6IMY2eLrrHp2MkVO836+nk5GSyvcY/goUiT1IcnXPiTdyeGiWwUcseN8rQ06X4b6GxbNq7fQuEndkbSA=
